server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cddofficial/config-repo-demo
          username: 
          password: 

encrypt:  key: foo