spring:  application:    name: microservice-gateway-zuul 
server:  port: 8040  
eureka:  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/       defaultZone: http://cdd:123456@localhost:8761/eureka
  instance:    prefer-ip-address: true       zuul:  prefix: /simple  strip-prefix: true