spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix-propagation
    
server:
  port: 8010

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://cdd:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

#超时时间设为5秒
hystrix.command.serverMethod.execution.isolation.thread.timeoutInMilliseconds: 5000